language: php

php:
  - 7.0
  - 7.1

env:
  global:

before_install: composer validate --strict

install: composer install

before_script:
  - composer lint
  - mysql -u root -e "GRANT ALL PRIVILEGES ON wp_tests.* TO wp IDENTIFIED BY 'password';"

script: composer test
